### ISSUE TITLE
Can't set Control+<arrow key> since updating to 1.1.1

### ISSUE THREAD

**Issue by feross** [eczarny/spectacle#689]
Version 1.1.1 (657)

<img width="565" alt="screen shot 2016-12-18 at 4 06 52 am" src="https://cloud.githubusercontent.com/assets/121766/21293379/7fe2c260-c4d7-11e6-8aac-1c00973b1875.png">

Since accepting the 1.1.1 update, I can't seem to use Control+arrow direction as a shortcut anymore.

**Comment by feross** [comment]
Just downgraded to 1.1.0 again and confirmed that it works again. So, looks like a bug to me!

**Comment by eczarny** [comment]
Does ctrl+up and ctrl+down work? I'm guessing ctrl+left and ctrl+right don't work since they are used by Mission Control. If so Spectacle should be displaying an error saying those shortcuts are already in use.

Try disabling those Mission Control shortcuts to see if Spectacle can use them.

**Comment by eczarny** [comment]
I think fa0dbf97543e5c7433b40c44f4e1128764dd3463 will help here. The problem I've been seeing is when Mission Control is using these two shortcuts for its own purposes. Spectacle should be flagging them as already in use.

**Comment by eczarny** [comment]
@feross do you mind testing out this build to see if the issue is resolved?

https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.2b.zip

**Comment by mabrodeur** [comment]
@eczarny Just tested, it now works with `ctrl` key

**Comment by kcparashar** [comment]
`Command` + `Option` + `Space` doesn't work either as of `Version 1.1.1 (657)`

**Comment by eczarny** [comment]
@kcparashar does the 1.2b build of Spectacle I linked above fix the problem for you?

**Comment by kcparashar** [comment]
@eczarny Yep resolved in the 1.2b build! Thanks!

**Comment by feross** [comment]
> The problem I've been seeing is when Mission Control is using these two shortcuts for its own purposes.

I removed the Mission Control shortcuts and still experienced the issue.

But things work with the new build. Cheers!
